project:
  type: website
  output-dir: _site

website:
  title: "Jon Oxford"
  navbar:
    left:
      - href: index.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
